services:
  db:
    image: postgres:16
    restart: always
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=labmate
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "labmate"]
      interval: 10s
      timeout: 5s
      retries: 5

  reverse-proxy:
    image: traefik:v3.1
    command: 
      - "--providers.docker"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=labmate@ant0n.uk"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entryPoints.web.http.redirections.entrypoint.to=websecure"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CF_DNS_API_TOKEN=$CF_DNS_API_TOKEN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt

  labmate:
    image: ghcr.io/antgobar/labmate:prod
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.labmate.rule=Host(`ant0n.uk`)"
      - "traefik.http.routers.labmate.entrypoints=websecure"
      - "traefik.http.routers.labmate.tls.certresolver=myresolver"
    volumes:
      - .:/code
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST=db
      - POSTGRES_DB=labmate
      - ADMIN_PASSWORD=$ADMIN_PASSWORD
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  letsencrypt:
