services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: labmateuser
      POSTGRES_PASSWORD: labmatepassword
      POSTGRES_DB: labmatedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db 

  app:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://labmateuser:labmatepassword@db/labmatedb
      ADMIN_PASSWORD: admin
    depends_on:
      - db

volumes:
  postgres_data:
