services:
  db:
    image: postgres:16
    restart: always
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=labmate
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "labmate"]
      interval: 10s
      timeout: 5s
      retries: 5

  reverse-proxy:
    image: traefik:v3.1
    command: 
      - "--api.insecure=true" # needed for the traefik dashboard
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "8080:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  labmate:
    image: ghcr.io/antgobar/labmate:prod
    volumes:
      - .:/code
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST=db
      - POSTGRES_DB=labmate
      - ADMIN_PASSWORD=$ADMIN_PASSWORD
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
