"""rename field

Revision ID: 0e30a26e8d05
Revises: a0e404285fa0
Create Date: 2024-08-18 23:22:51.265685

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "0e30a26e8d05"
down_revision: Union[str, None] = "a0e404285fa0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
