"""measurement_created_at

Revision ID: 1d0322f9be4c
Revises: 94f982330bbd
Create Date: 2024-08-26 13:39:01.907303

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1d0322f9be4c"
down_revision: Union[str, None] = "94f982330bbd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("measurements", sa.Column("created_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("measurements", "created_at")
    # ### end Alembic commands ###
