"""exp_sample assc table

Revision ID: 1fdcbbb91d46
Revises: 0e30a26e8d05
Create Date: 2024-08-19 19:47:29.733754

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "1fdcbbb91d46"
down_revision: Union[str, None] = "0e30a26e8d05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
