"""contact_form

Revision ID: 471fa593daa9
Revises: 1d0322f9be4c
Create Date: 2024-08-26 20:33:17.343812

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "471fa593daa9"
down_revision: Union[str, None] = "1d0322f9be4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
