"""contact_form_created_at

Revision ID: 53b8e31436c3
Revises: 471fa593daa9
Create Date: 2024-08-26 20:58:04.559094

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "53b8e31436c3"
down_revision: Union[str, None] = "471fa593daa9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contact_responses", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contact_responses", "created_at")
    # ### end Alembic commands ###
