"""restrict_chars

Revision ID: 65ab59849b03
Revises: 53b8e31436c3
Create Date: 2024-08-26 21:28:14.727124

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "65ab59849b03"
down_revision: Union[str, None] = "53b8e31436c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
