"""step no

Revision ID: 66c52f3da34a
Revises: aa379ec1c752
Create Date: 2024-10-13 20:04:57.531513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66c52f3da34a'
down_revision: Union[str, None] = 'aa379ec1c752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('methods', sa.Column('step_no', sa.Integer(), nullable=True))
    op.drop_constraint('methods_step_key', 'methods', type_='unique')
    op.create_unique_constraint(None, 'methods', ['step_no'])
    op.drop_column('methods', 'step')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('methods', sa.Column('step', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'methods', type_='unique')
    op.create_unique_constraint('methods_step_key', 'methods', ['step'])
    op.drop_column('methods', 'step_no')
    # ### end Alembic commands ###
