"""first revision

Revision ID: 71c38c37a482
Revises:
Create Date: 2024-08-18 23:10:03.065639

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "71c38c37a482"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
