"""measurements

Revision ID: 94f982330bbd
Revises: b3571bd3acf5
Create Date: 2024-08-24 23:29:01.194951

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "94f982330bbd"
down_revision: Union[str, None] = "b3571bd3acf5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
