"""rename field

Revision ID: a0e404285fa0
Revises: 6e1ca1d1e441
Create Date: 2024-08-18 23:18:23.058789

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "a0e404285fa0"
down_revision: Union[str, None] = "6e1ca1d1e441"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
