"""methods

Revision ID: aa379ec1c752
Revises: ad095f2628c1
Create Date: 2024-10-13 20:04:11.649203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa379ec1c752'
down_revision: Union[str, None] = 'ad095f2628c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('methods', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'methods', ['step'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'methods', type_='unique')
    op.drop_column('methods', 'is_completed')
    # ### end Alembic commands ###
