"""unique_primary_key

Revision ID: ad095f2628c1
Revises: aa506bfcffe0
Create Date: 2024-08-30 12:50:30.703405

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ad095f2628c1"
down_revision: Union[str, None] = "aa506bfcffe0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_contact_responses_id", table_name="contact_responses")
    op.create_index(
        op.f("ix_contact_responses_id"), "contact_responses", ["id"], unique=True
    )
    op.drop_index("ix_experiments_id", table_name="experiments")
    op.create_index(op.f("ix_experiments_id"), "experiments", ["id"], unique=True)
    op.drop_index("ix_lab_samples_id", table_name="lab_samples")
    op.create_index(op.f("ix_lab_samples_id"), "lab_samples", ["id"], unique=True)
    op.drop_index("ix_measurements_id", table_name="measurements")
    op.create_index(op.f("ix_measurements_id"), "measurements", ["id"], unique=True)
    op.drop_index("ix_users_id", table_name="users")
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.create_index("ix_users_id", "users", ["id"], unique=False)
    op.drop_index(op.f("ix_measurements_id"), table_name="measurements")
    op.create_index("ix_measurements_id", "measurements", ["id"], unique=False)
    op.drop_index(op.f("ix_lab_samples_id"), table_name="lab_samples")
    op.create_index("ix_lab_samples_id", "lab_samples", ["id"], unique=False)
    op.drop_index(op.f("ix_experiments_id"), table_name="experiments")
    op.create_index("ix_experiments_id", "experiments", ["id"], unique=False)
    op.drop_index(op.f("ix_contact_responses_id"), table_name="contact_responses")
    op.create_index(
        "ix_contact_responses_id", "contact_responses", ["id"], unique=False
    )
    # ### end Alembic commands ###
