"""measurements

Revision ID: b3571bd3acf5
Revises: e09999055385
Create Date: 2024-08-24 23:28:06.056494

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "b3571bd3acf5"
down_revision: Union[str, None] = "e09999055385"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
