"""measurements_variables

Revision ID: e09999055385
Revises: 598e989668ff
Create Date: 2024-08-24 23:27:02.560455

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e09999055385"
down_revision: Union[str, None] = "598e989668ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("measurements", sa.Column("variables", sa.JSON(), nullable=True))
    op.drop_column("measurements", "unit")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "measurements",
        sa.Column("unit", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.drop_column("measurements", "variables")
    # ### end Alembic commands ###
