"""temp removal

Revision ID: e1775c992e1d
Revises: 1b6df9c28b64
Create Date: 2024-08-26 22:17:48.430130

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e1775c992e1d"
down_revision: Union[str, None] = "1b6df9c28b64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_contact_responses_email", table_name="contact_responses")
    op.drop_index("ix_contact_responses_id", table_name="contact_responses")
    op.drop_index("ix_contact_responses_name", table_name="contact_responses")
    op.drop_table("contact_responses")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact_responses",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "message", sa.VARCHAR(length=2000), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="contact_responses_pkey"),
    )
    op.create_index(
        "ix_contact_responses_name", "contact_responses", ["name"], unique=False
    )
    op.create_index(
        "ix_contact_responses_id", "contact_responses", ["id"], unique=False
    )
    op.create_index(
        "ix_contact_responses_email", "contact_responses", ["email"], unique=False
    )
    # ### end Alembic commands ###
