"""contact form table

Revision ID: ff34750b3fbc
Revises: e1775c992e1d
Create Date: 2024-08-26 22:31:15.723256

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "ff34750b3fbc"
down_revision: Union[str, None] = "e1775c992e1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
